Book.GUI/Areas/Admin/Controllers/BookController.cs
using BookShop.DAL.Repositories.IRepositories;
using BookShop.Models.ViewModels;
using BookShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Linq;

namespace BookShop.GUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticRole.RoleAdmin + "," + StaticRole.RoleEmployee)]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BookController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            var bookVM = new BookVM();
            bookVM.Book = new Book();
            bookVM.Genres = _unitOfWork.Genre.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            bookVM.Authors = _unitOfWork.Author.GetAll().Select(i => new SelectListItem
            {
                Text = i.FullName,
                Value = i.Id.ToString()
            });
            bookVM.Publishers = _unitOfWork.Publisher.GetAll().Select(i => new SelectListItem
            {
                Text = i.PublisherName,
                Value = i.Id.ToString()
            });


            if (id == null)
            {
                return View(bookVM);
            }

            //// Eager load both BookGenre and BookAuthor
            bookVM.Book = _unitOfWork.Book.GetAll(
                    includeProperties: "BookGenres.Genre,BookAuthors.Author"
                    )
                .Where(b => b.Id == id.GetValueOrDefault())
                .FirstOrDefault();

            bookVM.SelectedGenres = bookVM.Book.BookGenres.Select(g => g.GenreId);
            bookVM.SelectedAuthors = bookVM.Book.BookAuthors.Select(a => a.AuthorId);

            if (bookVM.Book == null)
            {
                return NotFound();
            }

            return View(bookVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(BookVM bookVM)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(webRootPath, @"images\books");
                    var fileExtention = Path.GetExtension(files[0].FileName);

                    if (bookVM.Book.ImageUrl != null)
                    {
                        var imgPath = Path.Combine(webRootPath, bookVM.Book.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(imgPath))
                        {
                            System.IO.File.Delete(imgPath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(upload, fileName + fileExtention), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    bookVM.Book.ImageUrl = @"\images\books\" + fileName + fileExtention;
                }
                else
                {
                    //// Update when not change the img
                    if (bookVM.Book.Id != 0)
                    {
                        var book = _unitOfWork.Book.Get(bookVM.Book.Id);
                        bookVM.Book.ImageUrl = book.ImageUrl;
                    }
                }

                if (bookVM.Book.Id == 0)
                {
                    _unitOfWork.Book.Add(bookVM.Book);
                    _unitOfWork.Save();

                    AddBookGenreAndAuthor(bookVM);
                }
                else
                {
                    //// First delete the existing genre and author
                    DeleteBookGenreAndAuthor(bookVM.Book.Id);

                    //// Update the book
                    _unitOfWork.Book.Update(bookVM.Book);

                    //// Readd new genre and author
                    AddBookGenreAndAuthor(bookVM);
                }


                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(bookVM);
        }

        /// <summary>
        /// This method use to add bookgenre and bookauthor
        /// </summary>
        /// <param name="bookVM">Book View Model</param>
        private void AddBookGenreAndAuthor(BookVM bookVM)
        {
            //// Add list book author
            foreach (var item in bookVM.SelectedAuthors)
            {
                _unitOfWork.BookAuthor.Add(new BookAuthor(bookVM.Book.Id, item));
            }

            //// Add list book genre
            foreach (var item in bookVM.SelectedGenres)
            {
                _unitOfWork.BookGenre.Add(new BookGenre(bookVM.Book.Id, item));
            }
        }

        /// <summary>
        /// This method use to remove bookgenre and book author
        /// </summary>
        /// <param name="bookId">Book Id</param>
        private void DeleteBookGenreAndAuthor(int bookId)
        {
            _unitOfWork.BookAuthor.RemoveAllBookAuthorOfABook(bookId);

            _unitOfWork.BookGenre.RemoveAllBookGenreOfABook(bookId);
        }

        #region Call API
        [HttpGet]
        public IActionResult GetAll()
        {
            var books = _unitOfWork.Book
                .GetAll(
                includeProperties:
                "BookAuthors.Author,BookGenres.Genre,Publisher");

            return Json(new { data = books });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var book = _unitOfWork.Book.Get(id);
            if (book == null)
            {
                return Json(new { success = false, message = "Error while deleting!" });
            }

            if (book.ImageUrl != null)
            {
                string webRootPath = _webHostEnvironment.WebRootPath;
                var imgPath = Path.Combine(webRootPath, book.ImageUrl.TrimStart('\\'));

                if (System.IO.File.Exists(imgPath))
                {
                    System.IO.File.Delete(imgPath);
                }
            }

            _unitOfWork.Book.Remove(book);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful!" });
        }
        #endregion
    }
}

Book.GUI/Areas/Admin/Controllers/GenreController.cs
using BookShop.DAL.Repositories.IRepositories;
using BookShop.Models.ViewModels;
using BookShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.GUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticRole.RoleAdmin + "," + StaticRole.RoleEmployee)]
    public class GenreController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public GenreController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            var genre = new Genre();
            if (id==null)
            {
                return View(genre);
            }

            genre = _unitOfWork.Genre.Get(id.GetValueOrDefault());

            if (genre==null)
            {
                return NotFound();
            }

            return View(genre);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Genre genre)
        {
            if (ModelState.IsValid)
            {
                if (genre.Id == 0)
                {
                    _unitOfWork.Genre.Add(genre);
                }
                else
                {
                    _unitOfWork.Genre.Update(genre);
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(genre);
        }

        #region Call API
        [HttpGet]
        public IActionResult GetAll()
        {
            var genres = _unitOfWork.Genre.GetAll();
            return Json(new { data = genres});
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var genre = _unitOfWork.Genre.Get(id);
            if(genre == null)
            {
                return Json(new { success = false, message = "Error while deleting!" });
            }

            _unitOfWork.Genre.Remove(genre);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful!" });
        }
        #endregion
    }
}

Book.GUI/Areas/Admin/Controllers/OrderController.cs
using BookShop.DAL.Repositories.IRepositories;
using BookShop.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.GUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            var order = new Order();
            if (id==null)
            {
                return View(order);
            }

            order = _unitOfWork.Order.Get(id.GetValueOrDefault());

            if (order==null)
            {
                return NotFound();
            }

            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Order order)
        {
            if (ModelState.IsValid)
            {
                if (order.Id == 0)
                {
                    _unitOfWork.Order.Add(order);
                }
                else
                {
                    _unitOfWork.Order.Update(order);
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(order);
        }

        #region Call API
        [HttpGet]
        public IActionResult GetAll()
        {
            var orders = _unitOfWork.Order.GetAll();
            return Json(new { data = orders});
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var order = _unitOfWork.Order.Get(id);
            if(order == null)
            {
                return Json(new { success = false, message = "Error while deleting!" });
            }

            _unitOfWork.Order.Remove(order);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful!" });
        }
        #endregion
    }
}

Book.GUI/Areas/Admin/Controllers/UserController.cs
using BookShop.DAL.Data;
using BookShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace BookShop.GUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticRole.RoleAdmin)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }


        #region Call API
        [HttpGet]
        public IActionResult GetAll()
        {
            var users = _db.ApplicationUsers.ToList();
            var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();

            foreach (var user in users)
            {
                var roleId = userRoles.FirstOrDefault(u => u.UserId == user.Id)
                                      .RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }

            return Json(new { data = users });
        }

        [HttpPost]
        public IActionResult LockOrUnlock([FromBody] string id)
        {
            var user = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);

            if (user == null)
            {
                return Json(new { success = false, message = "Error while operating" });
            }

            if(user.LockoutEnd!=null && user.LockoutEnd > DateTime.Now)
            {
                // current is lock
                user.LockoutEnd = DateTime.Now;
            }
            else
            {
                user.LockoutEnd = DateTime.Now.AddYears(222);
            }
            _db.SaveChanges();

            return Json(new { success = true, message = "Successfully" });
        }
        #endregion
    }
}

Book.GUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookWeb.GUI</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/material-dashboard.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

</head>
<body>
    <div class="wrapper ">
        <div class="sidebar" data-color="purple" data-background-color="white">
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

                Tip 2: you can also add an image using data-image tag
            -->
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text logo-mini">
                    CT
                </a>
                <a href="http://www.creative-tim.com" class="simple-text logo-normal">
                    Creative Tim
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="nav-item active  ">
                        <a class="nav-link" href="#0">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <!-- your sidebar here -->
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="Admin" asp-controller="Author" asp-action="Index">
                            <i class="fas fa-pen-alt"></i>
                            <p>Author</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="Admin" asp-controller="Book" asp-action="Index">
                            <i class="fas fa-book"></i>
                            <p>Book</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="Admin" asp-controller="Genre" asp-action="Index">
                            <i class="fas fa-filter"></i>
                            <p>Genre</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
                            <i class="fab fa-opencart"></i>
                            <p>Order</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="Admin" asp-controller="OrderDetail" asp-action="Index">
                            <i class="fas fa-cart-arrow-down"></i>
                            <p>Order Detail</p>
                        </a>
                    </li>
                    <li class="nav-item pb-3">
                        <a class="nav-link" asp-area="Admin" asp-controller="Publisher" asp-action="Index">
                            <i class="fas fa-place-of-worship"></i>
                            <p>Publiser</p>
                        </a>
                    </li>
                    <li class="nav-item pb-3">
                        <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">
                            <i class="fas fa-user"></i>
                            <p>User</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" href="javascript:;">Dashboard</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:;">
                                    <i class="material-icons">notifications</i> Notifications
                                </a>
                            </li>
                            <!-- your navbar here -->
                        </ul>
                    </div>
                </div>
                <partial name="_LoginPartial" />
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <!-- your content here -->
                    @RenderBody()
                </div>
            </div>
            <!--<footer class="footer">
                <div class="container-fluid">
                    <nav class="float-left">
                        <ul>
                            <li>
                                <a href="https://www.creative-tim.com">
                                    Creative Tim
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright float-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>, made with <i class="material-icons">favorite</i> by
                        <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
                    </div>-->
            <!-- your footer here -->
            <!--</div>
            </footer>-->
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Book.GUI/Views/Shared/_CreateAndBackButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back</a>
    </div>
</div>

Book.GUI/Views/Shared/_EditAndBackButton.cshtml
@model int

<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Edit</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back</a>
    </div>
</div>

Book.GUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book.GUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book.GUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Book.GUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>